pipeline {
  agent any

  parameters {
    choice(name: 'ENVIRONMENT', choices: ['dev', 'uat'], description: 'Choose environment to deploy')
  }

  environment {
    AWS_DEFAULT_REGION = "us-east-1"
    TFVARS_FILE = "terraform.tfvars.${params.ENVIRONMENT}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        sh 'terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh "terraform plan -var-file=${TFVARS_FILE}"
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: "Approve apply for ${params.ENVIRONMENT}?"
        sh "terraform apply -auto-approve -var-file=${TFVARS_FILE}"
      }
    }
  }
}
